# Generated by Django 5.1.3 on 2024-12-04 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial_migration2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=100, unique=True)),
                ('driver_name', models.CharField(default='Unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mms_id', models.CharField(max_length=100, unique=True)),
                ('dedicated_phone_number', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=100, unique=True)),
                ('truck_source', models.CharField(default='Unknown', max_length=255)),
                ('truck_first_stop', models.CharField(default='Unknown', max_length=255)),
                ('truck_status', models.CharField(choices=[('enroute', 'En Route'), ('stopped', 'Stopped'), ('delayed', 'Delayed')], default='enroute', max_length=50)),
                ('max_volume', models.FloatField(default=0.0)),
                ('current_volume', models.FloatField(default=0.0)),
                ('max_weight', models.FloatField(default=0.0)),
                ('current_weight', models.FloatField(default=0.0)),
                ('threshold_volume', models.FloatField(default=0.0)),
                ('filled_capacity', models.FloatField(default=0.0)),
                ('mms_allocated_id', models.CharField(default='Not Assigned', max_length=100)),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.driver')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100)),
                ('truck_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.truck')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100, unique=True)),
                ('parcel_weight', models.FloatField(default=0.0)),
                ('parcel_volume', models.FloatField(default=0.0)),
                ('parcel_destination', models.CharField(default='Unknown', max_length=255)),
                ('truck_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.truck')),
            ],
        ),
    ]
