# Generated by Django 5.1.3 on 2024-12-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='route',
            field=models.TextField(default=''),
        ),
    ]
