# Generated by Django 5.1.3 on 2024-12-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_truck_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='truck_first_stop',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='truck_source',
        ),
    ]
