# Generated by Django 5.1.3 on 2024-12-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_truck_truck_first_stop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_id',
        ),
    ]
