# Generated by Django 5.1.3 on 2024-12-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_remove_driver_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='current_destination',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='truck',
            name='current_location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
