# Generated by Django 5.1.3 on 2024-12-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_truck_current_destination_truck_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='current_destination',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='truck',
            name='current_location',
            field=models.IntegerField(default=0),
        ),
    ]
