# Generated by Django 5.1.3 on 2024-12-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_truck_current_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
