# Generated by Django 5.1.3 on 2024-12-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_truck_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='truck_id',
        ),
        migrations.AddField(
            model_name='parcel',
            name='bag_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_id', models.IntegerField(unique=True)),
                ('truck_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.truck')),
            ],
        ),
    ]
