# Generated by Django 5.1.3 on 2024-12-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_databasechangelog_databasechangeloglock_tcattributes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driver_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='parcel_volume',
            new_name='volume',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='parcel_weight',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='parcel_destination',
        ),
        migrations.AddField(
            model_name='bag',
            name='current_destination',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bag',
            name='current_location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bag',
            name='destination',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parcel',
            name='current_destination',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parcel',
            name='current_location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parcel',
            name='destination',
            field=models.IntegerField(default=0),
        ),
    ]
