# Generated by Django 5.1.3 on 2024-12-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_rename_driver_name_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='bag_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
