# Generated by Django 5.1.3 on 2024-12-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_alter_parcel_bag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='truck_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.truck'),
        ),
    ]
