# Generated by Django 5.1.3 on 2024-12-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_alter_bag_truck_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='truck_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thirdpartylogistics',
            name='truck_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
