# Generated by Django 5.1.3 on 2024-12-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_alter_bag_truck_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bag',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
