# Generated by Django 5.1.3 on 2024-12-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_bag_volume_bag_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='is_at_warehouse',
            field=models.BooleanField(default=0),
        ),
    ]
