# Generated by Django 5.1.3 on 2024-12-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_truck_is_at_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='is_on_route',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='truck',
            name='live_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_status',
            field=models.CharField(default='enroute', max_length=50),
        ),
    ]
