# Generated by Django 5.1.3 on 2024-12-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_truck_is_on_route_truck_live_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck_capacity_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=100, unique=True)),
                ('actual_id', models.IntegerField(default=-1)),
                ('current_location', models.IntegerField(default=0)),
                ('filled_capacity', models.FloatField(default=0.0)),
            ],
        ),
    ]
