# Generated by Django 5.1.3 on 2024-12-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_truck_capacity_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMS_call_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=100)),
                ('actual_id', models.IntegerField(default=-1)),
                ('mms_id', models.CharField(max_length=100)),
                ('issues', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100)),
                ('current_location', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck_issue_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=100)),
                ('actual_id', models.IntegerField(default=-1)),
                ('issues', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck_live_status_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=100)),
                ('actual_id', models.IntegerField(default=-1)),
                ('live_status', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=100)),
                ('actual_id', models.IntegerField(default=-1)),
                ('current_location', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='issues',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='truck_capacity_log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='driver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='truck_capacity_log',
            name='truck_id',
            field=models.CharField(max_length=100),
        ),
    ]
