# Generated by Django 5.1.3 on 2024-12-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_mms_call_log_parcel_log_truck_issue_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_log',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='truck',
            name='route_estimated_arrival',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='truck_log',
            name='arrival_actual',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='truck_log',
            name='arrival_estimated',
            field=models.DateTimeField(null=True),
        ),
    ]
