# Generated by Django 5.1.3 on 2024-12-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_truck_route_estimated_departure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('token', models.TextField(default='')),
                ('truck_access', models.TextField(default='')),
                ('warehouse_access', models.TextField(default='')),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
