# Generated by Django 5.1.3 on 2024-12-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='truck_access',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='warehouse_access',
            field=models.TextField(),
        ),
    ]
