# Generated by Django 5.1.3 on 2024-12-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0024_alter_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='token',
        ),
        migrations.AlterField(
            model_name='users',
            name='truck_access',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='warehouse_access',
            field=models.TextField(null=True),
        ),
    ]
