# Generated by Django 5.1.3 on 2024-12-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0025_remove_users_token_alter_users_truck_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='is_delivered',
            field=models.BooleanField(default=0),
        ),
    ]
