# Generated by Django 5.1.3 on 2024-12-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0026_parcel_is_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_log',
            name='arrival_actual',
        ),
        migrations.RemoveField(
            model_name='truck_log',
            name='arrival_estimated',
        ),
        migrations.AddField(
            model_name='truck_log',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='truck_log',
            name='event_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='truck_log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
