# Generated by Django 5.1.3 on 2024-12-10 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0027_remove_truck_log_arrival_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_log',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
