# Generated by Django 5.1.3 on 2024-12-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0028_alter_truck_log_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_log',
            name='date',
        ),
    ]
