# Generated by Django 5.1.3 on 2024-12-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0030_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='issue',
        ),
        migrations.AddField(
            model_name='notifications',
            name='geofence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
