# Generated by Django 5.1.3 on 2024-12-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0031_remove_notifications_issue_notifications_geofence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='geofence',
            new_name='geofence_id',
        ),
    ]
