# Generated by Django 5.1.3 on 2024-12-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0036_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='geofence_id',
            field=models.IntegerField(null=True),
        ),
    ]
